#:schema ../override-schema.json

["21H.S04"]
name = "Understanding 1948: History, Memory, and Competing Narratives in Israel/Palestine"
prereqs = "None"
isVariableUnits = false
lectureUnits = 2
labUnits = 0
preparationUnits = 10
inCharge = "O. Marck"
description = "Examines the 1948 Arab-Israeli War as both a pivotal historical event and a subject of competing historiographical interpretations. Explores the social and political processes that led to the war, including the landscape of Mandatory Palestine, the rise of Zionist and Palestinian national movements, and the outbreak of violence following the UN partition plan. Addresses key debates – such as the origins of the war and the Palestinian refugee problem – and considers how 1948 has been remembered and contested in Israel, Palestine, and beyond."
