#:schema ../override-schema.json

["21L.003"]
name = "Reading Fiction: Jane Austen"

["21L.004"]
inCharge = "J. Sylvester, S. Tapscott"

["21L.016"]
inCharge = "S. (Frampton) Seed"

["21L.024"]
name = "Literature and Existentialism: Life, Death and Freedom"

["21L.027"]
name = "Children and Culture: Children Co-Creating Culture"

["21L.315"]
new = true
description = "Taught by Visiting Faculty Member! Examines particular texts and authors as having special merit and significance. Considers modern authors and filmmakers who have received such accolades as a Nobel Prize, a Pulitzer Prize, or an Oscar, as well as older authors who have been named as poets laureate, or honored by traditions of commentary, interpretation, and translation. Specific topics vary from term to term. May be repeated once for credit if the specific works studied differ. Confirm start and end dates on Literature website. Enrollment limited."

["21L.325"]
name = "Small Wonders: Small Wonders of the Everyday"

["21L.443"]
name = "Film Styles and Genres: Remakes and Remediations"

["21L.435"]
name = "Literature and Film: Indigenous Film and Literature"

["21L.481"]
name = "HIV/AIDS in American Culture: Black Lives and Queer Bodies"

["21L.613"]
inCharge = "S. (Frampton) Seed"

["21L.614"]
inCharge = "S. (Frampton) Seed"

["21L.703"]
name = "Studies in Drama: Stoppard, Churchill and Company"

["21L.704"]
name = "Studies in Poetry: The Poetry of Witness"

["21L.705"]
name = "Major Authors: Epics of Human Choice: Spenser's Faerie Queene and Milton's Paradise Lost"

["21L.706"]
name = "Studies in Film: Color in Film"

["21L.903"]
inCharge = "S. (Frampton) Seed"
