#:schema ../override-schema.json

["21L.003"]
name = "Reading Fiction: Jane Austen"

["21L.024"]
name = "Literature and Existentialism: Life, Death and Freedom"

["21L.027"]
name = "Children and Culture: Children Co-Creating Culture"

["21L.443"]
name = "Film Styles and Genres: Remakes and Remediations"

["21L.435"]
name = "Literature and Film: Indigenous Film and Literature"

["21L.481"]
name = "HIV/AIDS in American Culture: Black Lives and Queer Bodies"

["21L.703"]
name = "Studies in Drama: Stoppard, Churchill and Company"

["21L.704"]
name = "Studies in Poetry: The Poetry of Witness"

["21L.705"]
name = "Major Authors: Epics of Human Choice: Spenser's Faerie Queene and Milton's Paradise Lost"

["21L.706"]
name = "Studies in Film: Color in Film"
