#:schema ./override-schema.json
# Course 1 special subjects (iap/spring 2025)

['1.S977']
level = "G"
name = "Structural Mechanics and Design M-Eng NYC Cohort Trip"
inCharge = "Professor John. Ochsendorf"
description = "Each year over IAP, the Structural Mechanics and Design M-Eng cohort along with Professor John Ochsendorf go on a multi-day tour of New York City. Throughout the trip, the group visits over a dozen companies and sites each day, allowing students to get hands-on experience in the world of structural engineering.  Additionally, you’ll stop by several buildings to see the architectural techniques and structures you study here, applied in person. This year, students will have the opportunity to earn 3 units for this trip by registering for 1.S977 and completing a project on an assigned structure.. These units can be applied towards the CEE restricted elective requirement. "

['1.S981']
level = "G"
meets = "1.S992"
name = "Concrete Science and Engineering"
inCharge = "Professor Admir Masic"
isVariableUnits = false
lectureUnits = 2
labUnits = 3
preparationUnits = 7
description = "Delves into the chemistry, multiscale structure, sustainability, and advanced engineering of cementitious materials. Key topics include ancient and modern cements, hydration and deterioration mechanisms, carbon footprint reduction, and life cycle assessment. Students gain hands-on experience with advanced characterization techniques (SEM/EDS, indentation, spectroscopies) and explore innovations like self-healing and multifunctional concretes. Industry insights, case studies, and a Sustainable Concrete Design Competition prepare students to tackle real-world challenges in cement and concrete science, equipping them to meet the demands of sustainable engineering. Graduate students complete additional requirements."

['1.S992']
level = "U"
meets = "1.S981"
name = "Concrete Science and Engineering"
inCharge = "Professor Admir Masic"
isVariableUnits = false
lectureUnits = 2
labUnits = 3
preparationUnits = 7
description = "Delves into the chemistry, multiscale structure, sustainability, and advanced engineering of cementitious materials. Key topics include ancient and modern cements, hydration and deterioration mechanisms, carbon footprint reduction, and life cycle assessment. Students gain hands-on experience with advanced characterization techniques (SEM/EDS, indentation, spectroscopies) and explore innovations like self-healing and multifunctional concretes. Industry insights, case studies, and a Sustainable Concrete Design Competition prepare students to tackle real-world challenges in cement and concrete science, equipping them to meet the demands of sustainable engineering. Graduate students complete additional requirements."
