#:schema ./override-schema.json
# Course 12 special subjects (fall 2025)

['12.S593']
name = "Special Seminar in EAPS-Exploring Solar System Surfaces (No Spacesuit Required)"
description = "Investigates the diverse surfaces of planetary bodies throughout our Solar System through the lens of remote sensing and robotic exploration. Examines how mission data reveals the formation, evolution, and current state of rocky planets, icy moons, and small bodies. Compares and contrasts geological processes across different planetary environments, from Mercury's extreme temperature variations to the subsurface oceans of Europa and Enceladus. Topics may include impact cratering; volcanism; tectonics; weathering and erosion processes; sedimentary deposits; glacial and periglacial features; and the search for habitable environments. Analyzes datasets of planetary surfaces from past and current missions (Cassini, New Horizons, OSIRIS-REx, Mars rovers, and more) alongside recent scientific literature. Emphasizes critical reading, student-led discussions, and comparative planetology approaches, with a component of hypothesis-driven mission concepts driven by current scientific advances."
inCharge = "G. Stucky de Quay"
level = "G"
isVariableUnits = true

['12.S680']
name = "Space Plasmas and Planetary Environments"
description = "Introduces the fundamentals of space plasma dynamics in planetary and interplanetary environments explored remotely and by spacecraft, including foundations of plasma dynamics (from single particle motion through fluid-like motion to waves and turbulence), solar wind and its effects on planetary environments and impact on technology. Special focus on using state-of-the-art computational models and spacecraft data to drive mission planning and scientific discovery, with applications in hazardous radiation prediction, detection of planetary dynamos and planetary magnetism, detection of ocean worlds , the magnetic history of the solar system, and the role of stellar winds in atmospheric escape and planetary habitability. 12.S680 is letter graded. 12.S681 is p/d/f."
inCharge = "B. Weiss, R. Oran"
lectureUnits = 9
labUnits = 0
preparationUnits = 3
meets = "12.S681"

['12.S681']
name = "Space Plasmas and Planetary Environments"
description = "Introduces the fundamentals of space plasma dynamics in planetary and interplanetary environments explored remotely and by spacecraft, including foundations of plasma dynamics (from single particle motion through fluid-like motion to waves and turbulence), solar wind and its effects on planetary environments and impact on technology. Special focus on using state-of-the-art computational models and spacecraft data to drive mission planning and scientific discovery, with applications in hazardous radiation prediction, detection of planetary dynamos and planetary magnetism, detection of ocean worlds , the magnetic history of the solar system, and the role of stellar winds in atmospheric escape and planetary habitability. 12.S680 is letter graded. 12.S681 is p/d/f."
inCharge = "B. Weiss, R. Oran"
lectureUnits = 9
labUnits = 0
preparationUnits = 3
meets = "12.S680"
