#:schema ./override-schema.json
# Course 15 special subjects (fall 2025)

["15.S03"]
name = "SSIM: AI and Money"
level = "G"
lectureUnits = 3
labUnits = 0
preparationUnits = 6
description = "'AI & Money' examines the evolving impact of artificial inteligence on money & finance. The course helps equip students with critical reasoning skills to understand AI driven innovation in finance.\n\nWe will explore how machine learning, generative AI, and advanced analytics are rdefining customer interactions, investing, payments, risk management, trading, underwriting, and compliance. The course also will touch on real-world applications including cyber risk, fraud detection, and AI supply chain decisions.\n\nThe course will review how AI developments could impact markets, economics, and monetary policy. Students will gain an understanding of these emerging technologies, along with their regulatory frameworks around the globe."
inCharge = "Gary Gensler"
