#:schema ./override-schema.json
# Course 2 special subjects
# https://meche.mit.edu/featured-classes

['2.S981']
name = 'Engineering of Nanoscale Materials'
level = 'G'
lectureUnits = 4
labUnits = 0
preparationUnits = 8
isVariableUnits = false
prereqs = 'Physics II (GIR) or permission of instructor (undergrad can take it upon approval)'
description = '''
“Engineering of nanoscale materials” is designed for graduate students who want to pursueadvanced study in Micro/Nano technology. The course provides in-depth knowledge aboutlow dimensional materials (0D, 1D, and 2D) aswell as thin film 3D materials and theirapplications. Throughout the semester, methodsto fabricate nanoscale materials will betaught. Then students will go through fundamentallevels of i) thinfilm mechanics:stress/strain in films and thin film failureincluding delamination, cracking, and buckling, ii)phase equilibrium and diffusion in thin film solids, and iii) electronic/photonic properties ofnanoscale materials. With those knowledges, students will finally learn about the applicationsof such low dimensional materials. This isa 12-unit subject with two lectures (3 hour) andone recitation (1 hour)'''
url = 'https://meche.mit.edu/featured-classes'

['2.S990']
name = 'Fiber and Textile Engineering'
lectureUnits = 3
labUnits = 0
preparationUnits = 3
isVariableUnits = false
description = '''
The course will outline underlying physical and engineering principles that are used in engineering and manufacturing of fibers and textiles. These include fundamentals of polymer science, mechanical, thermal, and moisture transport engineering of fibrous media, visual color science and engineering, and friction and wear of polymer and composite fibrous materials. The students will practice analyzing how the material and structure of woven, knitted, and nonwoven textiles translates into their strength, stretchability, abrasion resistance, visible color and reflectance, passive cooling or heating, and anti-microbial and self-cleaning properties.

Students will study and analyze real-life examples including different commercial and specialty textiles and will learn to use the life cycle assessment analysis to identify and prioritize the materials, processes, and designs that have the greatest potential for the reduction the environmental impact of the textile and garment production. They will also study examples of textile/garment-related patent applications and will practice drafting applications for their design ideas.

Prereq (Grad): None/Prereq (Recommended Undergrad): 2.00, 2.001, 2.051'''
url = 'https://sboriskina.mit.edu/mit-courses-2020-2021'

['2.S992']
name = 'Teaching and Learning Mechanical Engineering with Generative AI'
level = 'G'
lectureUnits = 6
labUnits = 0
preparationUnits = 6
isVariableUnits = false
prereqs = 'an undergraduate degree in Mechanical Engineering; proficiency in Matlab or Python. (UG can particpate with permission of instructor)'
description = '''
Large Language Model (LLM) capabilities and environments. Use of GPT-4 in Mechanical Engineering: development of effective system and interactive prompts; critical assessment of GPT-generated results. Application of GPT to teaching and learning: solid mechanics, heat transfer, dynamics, and mechanical design. GPT user models: teacher and student roles. GPT for coding. GPT as database. GPT for image processing. GPT for symbolic computation. GPT for natural language interfaces. GPT for problem-solving en- vironments. GPT as test student. GPT as tutor. Projects requiring Matlab or Python programming within GPT-4 API and Chat contexts. Enrollment limited to 15 students.'''
url = 'https://meche.mit.edu/featured-classes'

['2.S994']
name = 'Pappalardo Lab Apprentice'
level = 'U'
lectureUnits = 6
labUnits = 0
preparationUnits = 6
isVariableUnits = false
prereqs = '2.670, 2.007, and permission from the instructor'
description = '''
The Pappalardo Apprentice series is designed to further develop fabrication skills, and provide mentor training and opportunities for peer-to-peer mentoring. Our objective is to push the boundaries of the lab experience, further developing your skills and the workspace as one of the safest, most productive, positive, and creative labs on campus. The program has two primary areas of emphasis:

1. Peer mentoring. You will be an undergraduate lab assistant for 2.007. This will require signing-on to a regularly scheduled 2.007 lab section and an additional three-hour lab block, to assist 2.007 students with fabrication, including machining, hand-tool use, materials and supplies assistance, brainstorming, and general peer-to-peer support.

2. Project work.Apprentices will participate in a series of seminars and clinics to refresh and further their fabrication knowledge and hands-on skills, including mill and lathe use, CAD/CAM, patternmaking, and casting (for senior project). Weekly seminars and practicum cover a variety of topics such as shop best practices, machine setup, chip formation, fixturing, material selection, and physical metallurgy. Junior apprentices will fabricate a Stirling engine and returning senior apprentices will focus on copper alloys, continuing to fabricate a replica of an 1899 anchor windlass from the Herreshoff Manufacturing Company, used on the famous New York 70 class sloops. Lab use for project work will be scheduled around 2.007 and requires apprentices to be largely self-directed.

This is a limited enrollment course, and students are encouraged to apply by sending resume and portfolio to pappalardolab@mit.edu, by midnight, December 31, 2023, with subject line “Pappalardo Lab Apprentice Application”. We will respond by January 19, 2024.'''
url = 'https://meche.mit.edu/featured-classes'

['2.S977']
name = "Founder's Journey: Launching and Scaling Hardware Startups"
level = 'U'
lectureUnits = 4
labUnits = 0
preparationUnits = 8
isVariableUnits = false
description = '''
Find and activate your entrepreneurial energy. What road are you embarking upon in starting a company, and what obstacles threaten your success? What is the core problem you’re solving? What else and who else will you need? If you’re thinking about starting a company, this class will enable you to learn by doing. You will solve real-life hardware startup problems, with the help of mentors and leaders from the Boston tech ecosystem. Topics you’ll explore include: challenges related to intellectual property negotiations with large incumbents; servicing equipment out in the wild; finding product-market fit; resolving manufacturing and quality issues; scaling up; and reaching strong gross margins. You’ll hear from guest speakers who will share their experiences – successful and unsuccessful – traveling this rocky path with its moments of crisis and triumph.

Although we will cover the basics of new venture creation, this is not a class about writing a business plan. Rather it’s about grasping the essence of the journey you’re about to undertake, and understanding the mindset required to be an entrepreneur developing a mechanical product. You will learn critical thinking skills that will help you assess the viability of a particular technology before you spend the years required to build a physical product. This class provides an exploration of leadership, innovation, and creativity as seen through the lens of a mechanical tech startup founder. You will gain broad insight into what’s required to turn a novel vision into a useful product.'''
url = 'https://meche.mit.edu/featured-classes'

['2.S979']
name = "Founder's Journey: Launching and Scaling Hardware Startups"
level = 'G'
lectureUnits = 4
labUnits = 0
preparationUnits = 8
isVariableUnits = false
description = '''
Find and activate your entrepreneurial energy. What road are you embarking upon in starting a company, and what obstacles threaten your success? What is the core problem you’re solving? What else and who else will you need? If you’re thinking about starting a company, this class will enable you to learn by doing. You will solve real-life hardware startup problems, with the help of mentors and leaders from the Boston tech ecosystem. Topics you’ll explore include: challenges related to intellectual property negotiations with large incumbents; servicing equipment out in the wild; finding product-market fit; resolving manufacturing and quality issues; scaling up; and reaching strong gross margins. You’ll hear from guest speakers who will share their experiences – successful and unsuccessful – traveling this rocky path with its moments of crisis and triumph.

Although we will cover the basics of new venture creation, this is not a class about writing a business plan. Rather it’s about grasping the essence of the journey you’re about to undertake, and understanding the mindset required to be an entrepreneur developing a mechanical product. You will learn critical thinking skills that will help you assess the viability of a particular technology before you spend the years required to build a physical product. This class provides an exploration of leadership, innovation, and creativity as seen through the lens of a mechanical tech startup founder. You will gain broad insight into what’s required to turn a novel vision into a useful product.'''
url = 'https://meche.mit.edu/featured-classes'

['2.S999']
name = 'Science and Technologies for Climate'
level = 'G'
lectureUnits = 3
labUnits = 0
preparationUnits = 3
isVariableUnits = false
prereqs = 'None'
description = '''
This seminar will explore challenges and opportunities of climate actions to decarbonize and reduce global temperature raise. We will welcome guest lecturers to share scientific challenges, recent discoveries, research translation, technology innovations, techno-economics and policy. Intended for undergraduate and graduate students who have interests to learn and get involved in energy and environment sustainability.'''
url = 'https://meche.mit.edu/featured-classes'
