#:schema ./override-schema.json
# Course 21A special subjects (spring 2025)

['21A.S01']
name = 'In the Trenches: Critical Global Health and Infrastructure Studies'
hassS = true
lectureUnits = 3
labUnits = 0
preparationUnits = 9
description = '''
This course explores how medical institutions come into being and the complexities of securing healthcare in our world today, especially for those who occupy marginal spaces of society. Beginning with an examination of the historical production of modern medical infrastructure, we consider the global health framework, and the tools/resources that marginalized peoples may draw from to grapple with emergent, widespread medical problems.'''

['21A.S02']
name = 'AI, Culture and Society'
lectureUnits = 2
labUnits = 0
preparationUnits = 4
description = '''
Artificial Intelligence has rapidly become a touchstone that many of us use to attempt to understand both enormous change in the present, and future opportunities and threats.  It has been variously viewed as an overarching peril to humanity and as a panacea that will solve our most intractable problems, from poverty and scarcity to climate change.

In this special topics course, “AI, Culture, and Society,” we will take a measured view of artificial intelligence technologies, with an emphasis on how they are actually affecting human society and culture.  We will combine perspectives from the social sciences, sciences, humanities, and the arts to explore the impact of AI on culture, the economy, science, law, education, and media. We will look at ethical issues bound up with AI, including privacy, bias in training data, social isolation, the use avatars, and increasing inequality.

This special topics course will be team taught by a group of faculty and other instructors from SHASS and across the Institute, including Graham Jones (Anthropology), Chris Boebel (MIT Open Learning), Arvind Satyanarayan (Computer Science), Susan Silbey (Anthropology/Sociology), and David Kaiser (STS).

Please note that due to space constraints, enrollment is limited to 25. If enrollment approaches that number, the instructor will give enrollment priority to students in the following order: Anthropology (21A) majors, Anthropology (21A) minors, Anthro concentrators, MIT undergraduates, and finally prospective cross-registrants from Harvard and Wellesley. Auditors will be accepted if space allows. Many thanks for your understanding.'''

# FALL 2025
# ['21A.S01']
# name = "Special Topic: Reimagining Indigeneity — Pathways of Identity, Cultural Expression, and Continuity in a Changing World"
# hassS = true
# lectureRawSections = ['4-163/W/0/11-2']
# lectureSections = [[[[66, 6]], '4-163']]
# inCharge = "J. Knox-Hayes, L. Jonas"
