#:schema ./override-schema.json
# Course 21G special subjects (fall 2025)

['21G.312']
name = "Basic Themes in French Literature and Culture: Science, Mysteries, and the Francophone World"
description = "Discover the unknown through the stories of the French-speaking world. This course is designed for intermediate and advanced French learners who are curious about science, innovation, and culture. Through exciting topics like Marie Curie, artificial intelligence, climate change, and science fiction, you will improve your French while exploring the mysteries and big questions of our time — from the past to the future, and from Europe to Africa to the Caribbean."
