#:schema ./override-schema.json
# Course 21M special subjects (fall 2025)

["21M.139"]
name = "Introduction to Arranging"
oldNumber = "Moments in Music: Composition B"
prereqs = " ''Permission of instructor''"
level = "U"
lectureUnits = 2
labUnits = 0
preparationUnits = 4
description = "Do you love listening to different covers of your favorite artists and songs? Are you intrigued by how a simple melody can be heard in a variety of colors and styles by different ensembles and instruments? The craft of arranging previously composed music, whether one’s own or another’s, is a way to express oneself musically in a variety of timbres, sounds, and textures. We will explore arranging as a bi-directional process: reducing a large score to a piano reduction and taking something as basic as a lead sheet melody with chords and expanding it to a larger vocal or instrumental piece. As a final project students will arrange a short piece of their choice for an a cappella or small instrumental ensemble.\n"
hassA = true
inCharge = "Garo Saraydarian"
url = "https://mta.mit.edu/music/class-schedule"

["21M.299"]
name = " Pirate Songs & Whaling Chanteys"
oldNumber = "Studies in Global Musics"
prereqs = "21M.030 or permission of Instructor"
level = "U"
lectureUnits = 3
labUnits = 0
preparationUnits = 9
description = "In this class, we will explore the role of music in U.S. maritime culture—both factual and fictional. From African American dockworkers’ songs in 19th-century Southern ports, to chanteys on American whaling vessels, to 20th-century folk revivals, to the singing pirates of film and video games, we will examine the musics that have animated the U.S.’s cultural fascination with the sea. Students will analyze primary source material including song collections, recordings, compositions, and viral social media videos. The class will involve frequent singing as an exploration of the repertoire and the cultural phenomenon of participatory chantey sings. No prior musical experience is needed (we will teach you to sing!).\n\n"
hassA = true
inCharge = "J. Maurer"
url = "https://mta.mit.edu/music/class-schedule"
