#:schema ./override-schema.json
# Course 6 special subjects (fall 2025)

["4.S14"]
name = "Architecture of Longevity: Designs for the Third Age"
description = "If Maria Montessori designed the tools and environment to meet the cognitive and physical stages of children, how might we similarly design our environment to meet the needs of the \"Young Old\"?\n\nThis workshop involves collecting, analyzing and drawing examples of designs for older adults from around the world across three ‘scales’: the body, the room, the street. Students in this course will help build an architectural index useful to help navigate the unprecedented \"Silver Tsunami\" that the United States and other industrialized countries have never before encountered, students will develop a variety of new designs on that can aid in alleviating the double housing and care crises that financially cripples 90% of older adults. Unless redressed, these financial burdens will in turn, fall on the shoulders of younger generations. How can we use architecture to reframe this opportunity and redesign our environments to fully embrace the cognitive, perceptual, and physical changes of humans across all ages — and thrive at each stage?"
inCharge = "R. Segal"
level = "G"
lectureUnits = 2
labUnits = 2
preparationUnits = 5

["4.S22"]
name = "System Change"
description = "How do you go from a moment of obligation to starting or accelerating a movement?\n\nThis course explores the difference between innovation, social innovation, and systems change for social impact. Students interested in navigating complex environmental and social problems will explore frameworks and case studies from real systems change innovators to develop a more comprehensive view of complex problems and the systems they are part of —systems that often keep those problems in place.\n\nIn the course, you will apply experiential tools and methods to interrogate your own call to action, strengths, and gaps to address complex problems or needs. You will gain an understanding of the importance of understanding problems from the impact target’s perspective and explore innovative ways to create a scalable movement that ultimately can change a system. The final deliverable from the course is writing a case study on system change based on detailed actor mapping and interviews where you share your deeper understanding of a system you care about."
inCharge = "Y. Jimenez"
level = "G"
lectureUnits = 2
labUnits = 0
preparationUnits = 7

["4.S24"]
name = "Creative Careers"
description = "How can you build your own creative practice in today’s international landscape—one that is sustainable, leverages innovation, and contributes meaningfully to the future of the cultural and creative sectors?\n\nThis half-semester course offers you, as a student in the arts, cultural, and creative fields, fundamental tools and strategies for designing your career as an independent professional or studio founder.\n\nYou will:\n\nA) Develop an understanding of the international framework of institutions, relationships, and policies that support professionals aiming to create impact through their creative practice—and learn how this knowledge can help you shape offerings that stand out and create a competitive advantage.\nB) Learn concepts and mechanisms commonly found in the economics of art and culture, and explore how critical issues can be transformed into strategic opportunities.\nC) Examine the diverse types of value generated by cultural production, discover how to combine them into distinctive offerings, and effectively communicate and market your work. You’ll also study business models within the creative industries and develop the adaptability to navigate evolving markets.\nD) Acquire practical skills in branding, legal business structures, and intellectual property—enabling you to protect and leverage your creative output while building a sustainable professional practice."
inCharge = "G. Picchi"
level = "G"
lectureUnits = 3
labUnits = 0
preparationUnits = 3

['4.S33']
name = "Beginner's Guide to Visualizing Data and Life-Like Processes in Digital Art"
inCharge = "W. Allstetter"
meets = "4.S37"
level = "G"
lectureUnits = 3
labUnits = 3
preparationUnits = 3
description = "This is an incredible opportunity to dive into the basics of biomimicry and natural algorithms in computational design and artificial life. Prior programming or modeling software experience is not needed. Advanced folks will be accommodated on an individual project-based track. Students learn about the cultural and visual implications of automation and biotechnological advancements driven by computational technology, exploring their aesthetic significance through the analysis of data and algorithms.\n\nThis course is designed as a beginner's guide to ethical solutions to design problems in computational design and data concerning nature through visualization and art. It is structured to be accessible and considerate of the broader impact of design decisions on communities, society, and culture. Students will receive a low-level, beginner-friendly introduction to the basics of data visualization in processing and Python, biomimicry, agent-based systems in Grasshopper visual coding, and C# and animation in Maya."

['4.S37']
name = "Beginner's Guide to Visualizing Data and Life-Like Processes in Digital Art"
inCharge = "W. Allstetter"
meets = "4.S33"
level = "U"
lectureUnits = 3
labUnits = 3
preparationUnits = 6
description = "This is an incredible opportunity to dive into the basics of biomimicry and natural algorithms in computational design and artificial life. Prior programming or modeling software experience is not needed. Advanced folks will be accommodated on an individual project-based track. Students learn about the cultural and visual implications of automation and biotechnological advancements driven by computational technology, exploring their aesthetic significance through the analysis of data and algorithms.\n\nThis course is designed as a beginner's guide to ethical solutions to design problems in computational design and data concerning nature through visualization and art. It is structured to be accessible and considerate of the broader impact of design decisions on communities, society, and culture. Students will receive a low-level, beginner-friendly introduction to the basics of data visualization in processing and Python, biomimicry, agent-based systems in Grasshopper visual coding, and C# and animation in Maya."

['4.S34']
name = "Publication as Worldmaking: Performative Approaches to Fiction and Publishing"
inCharge = "R. Majzoub"
level = "G"
lectureUnits = 3
labUnits = 3
preparationUnits = 6
description = "This course investigates the interdisciplinary and generative possibilities of publication, emphasizing its role as a practice of expanding public engagement and imagination. Throughout the semester, students will explore worldmaking strategies, speculative fiction and an array of publication methods ranging from traditional techniques—leveraging ACT and MIT’s extensive resources such as riso printing, book binding and maker labs—to experimental approaches in digital media, performance, political systems, architecture, contemporary art, design and AI.Specific expectations and/or deliverable product resulting from course."

["4.S43"]
name = "Applied Category Theory for Engineering Design"
description = "Considers the multiple trade-offs at various abstraction levels and scales when designing complex, multi-component systems. Covers topics from foundational principles to advanced applications, emphasizing the role of compositional thinking in engineering. Introduces category theory as a mathematical framework for abstraction and composition, enabling a unified and modular approach to modeling, analyzing, and designing interconnected systems. Showcases successful applications in areas such as dynamical systems and automated system design optimization, with a focus on autonomous robotics and mobility. Offers students the opportunity to work on their own application through a dedicated project in the second half of the term. \n\nStudents taking graduate version complete additional assignments."
lectureUnits = 3
labUnits = 1
preparationUnits = 8
level = "G"
inCharge = "G. Zardini"
same = "1.144"

["4.S65"]
name = "Decolonial Ecologies"
description = "This seminar examines the relationship between political ecology, ecological crises, and the process of (de)colonization. Students will critically analyze historical understandings of decolonization and contemporary proposals for decolonial ecologies. Following Stefanie K. Dunning’s invocation “May our egos die so that the world may live,” this seminar asks, how can we continually transform our praxis on a personal and structural level to create the possibility and space for decolonial ecologies? And whose imaginations are presently shaping our collective futures? Open for cross-registration. And open to undergraduates with instructor’s permission."
isVariableUnits = false
level = "G"
lectureUnits = 3
labUnits = 0
preparationUnits = 9
inCharge = "H. Gupta"
