#:schema ./override-schema.json
# Course 5 special subjects (spring 2025)

['5.S64']
name = "Advances in Interdisciplinary Science in Human Health and Disease"
description = "Introduces major principles, concepts, and clinical applications of biophysics, biophysical chemistry, and systems biology. Emphasizes biological macromolecular interactions, biochemical reaction dynamics, and genomics. Discusses current technological frontiers and areas of active research at the interface of basic and clinical science. Provides integrated, interdisciplinary training and core experimental and computational methods in molecular biochemistry and genomics."

['5.S72']
name = "Statistical Mechanics"
description = "Principles and methods of statistical mechanics. Classical and quantum statistics, grand ensembles, fluctuations, molecular distribution functions, and other topics in equilibrium statistical mechanics. Topics in thermodynamics and statistical mechanics of irreversible processes."
