#:schema ./override-schema.json
# Course 6 special subjects (fall 2025)

['6.S042']
name = "Computer Networks"
meets = "6.5820"
prereqs = "6.1800 or 6.1810, or permission of instructor"
inCharge = "H. Balikrishnan, M. Alizadeh"
description = "Topics on the engineering and analysis of network protocols and architecture, including architectural principles for designing heterogeneous networks; transport protocols; Internet routing; router design; congestion control and network resource management; wireless networks; network security; naming; overlay and peer-to-peer networks. Readings from original research papers. Semester-long project and paper. Students taking graduate version complete different assignments."

['6.5820']
meets = "6.S042"

["6.S044"]
name = "AI and Rationality"
same = "24.S00"
prereqs = "6.1200 or a subject in probability or logic"
inCharge = "L. Kaelbling, B. Hedden"
description = "This class brings together philosophical work on rationality – primarily in formal epistemology and decision theory – with work in AI on belief-formation and planning, with the aim of giving students interested in AI a more philosophically sophisticated understanding of rational agency and illustrating how attempts to design intelligent systems might shed light on human rationality. The distinction between “ideal” rationality and “bounded” rationality (which takes computational and memory limitations into account) will be a major theme throughout the course.\n\nWe begin with an overview of theories of rationality and agency, including classic discussions of whether it can make sense to attribute mental states like beliefs, desires, and intentions to artificial systems. We then focus on different aspects of rational agency – beliefs, desires/utilities, decision theory, planning and sequential decision-making, and multi-agent cases – before closing the course with a week on whether LLMs have beliefs and desires."

['6.S056']
name = "Hack Yourself: Data-driven Wellbeing and Learning"
inCharge = "A. Bell"
prereqs = "6.1000 or 6.100A"
description = "Did you know that celebrating a friend’s success is more important than supporting them during tough times? Or that taking a practice test improves memory 17% more than simply studying?  Or that time pressure decreases your creativity by 45%?\n\nPsychology is full of surprises, but simply knowing the facts isn’t enough.  In this course, you’ll take charge of your wellbeing and learning and develop leadership skills, coming away with a toolkit of over 60 sustainable positive habits.  In addition, you’ll explore data science methods to validate these positive psychology tools, gaining hands-on experience with AI and statistical analysis that you will be able apply across different fields.  Finally, you’ll develop skills for positive communication and effective persuasion through data and visualization."

['6.S061']
name = "Humane User Experience Design"
inCharge = "A. Satyanarayan"
same = "21A.S02"
meets = "21A.S10"
prereqs = "6.1010"
description = "Teaches an end-to-end user-centric design process focusing on developing humane (usable, joyful, whimsical) frontend user experiences for generative AI, grounded in anthropology. Topics include understanding human context (e.g., through observation, interviews, and user testing), qualitative data analysis, principles of effective and expressive visual and interaction design, frontend web application implementation, and user testing and ethical audits. Enrollment limited."

['6.S077']
name = "Life Science and Semiconductor"
meets = "6.S897"
inCharge = "A. Bahai, T. Heldt"

['6.S897']
name = "Life Science and Semiconductor"
meets = "6.S077"
inCharge = "A. Bahai, T. Heldt"

['6.S890']
name = "Topics in Mulitagent Learning"
prereqs = "6.1220 or 6.7201, 6.1200"
inCharge = "G. Farina"
url = "https://mit.edu/~gfarina/www/6S890"
description = "While machine learning techniques have had significant success in single-agent settings, an increasingly large body of literature has been studying settings involving several learning agents with different objectives. In these settings, standard training methods, such as gradient descent, are less successful and the simultaneous learning of the agents commonly leads to nonstationary and even chaotic system dynamics. \n\nMotivated by these challenges, this course presents the foundations of multi-agent systems from a combined game-theoretic, optimization and learning-theoretic perspective, building from matrix games (such as rock-paper-scissors) to stochastic games, imperfect information games, and games with non-concave utilities. We will present manifestations of these models in machine learning applications, from solving Go to multi-agent reinforcement learning, adversarial learning and broader multi-agent deep learning applications. We will discuss aspects of equilibrium computation and learning as well as the computational complexity of equilibria. We will also discuss how the different models and methods have allowed several recent breakthroughs in AI, including human- and superhuman-level agents for established games such as Go, Poker, Diplomacy, and Stratego. A tentative course syllabus can be found below."

['6.S892']
name = "Advanced Topics in Power Electronics"
prereqs = "6.6620 or equivalent"
inCharge = "D. Perreault"
description = "Advanced topics in analysis, design, manufacturing, and control of power electronics. Topics include: architectures and topologies for power electronics including soft-switched, resonant, high-frequency and switched-capacitor circuits; high-frequency power magnetics; advanced modeling and control methods; power components, devices, and materials; manufacturing methods; low-noise circuit design and filtering; circuit theory applications to power electronics; emerging technologies and applications in power conversion."

['6.S894']
name = "Accelerated Computing"
inCharge = "J. Ragan-Kelley"
prereqs = "6.1060, 6.1910"
description = "Project-based introduction to software performance engineering on specialized hardware and accelerators. Topics include fundamentals of accelerator architecture from a performance engineer’s perspective, accelerator programming models and tools, and analysis of accelerator performance."

['6.S896']
name = "Algorithmic Statistics"
prereqs = "6.1220 and 18.600 and 18.200 or equivalents, and grad-level mathematical maturity"
inCharge = "S. Hopkins"
description = "Introduction to algorithms and computational complexity for high-dimensional statistical inference problems, with focus on provable polynomial-time guarantees. Covers modern algorithm design techniques via convex programming and Sum of Squares method, graphical models as a language to describe complex but tractable high-dimensional learning problems and associated learning algorithms, and basics of complexity for statistical problems, including statistical query and low-degree lower bounds and reductions."

['6.S965']
name = "Digital Systems Laboratory II"
prereqs = "6.2050"
inCharge = "J. Steinmeyer"
description = "Continuation of topics introduced in Digital Systems Laboratory (6.205). Particular focus on modern design verification practices, System Verilog, and Universal Verification Methodology (UVM) as well as designing complex digital systems in hybrid platforms such as SoC and state-of-the-art RFSoC platforms. Weekly labs and final design project with emphasis on signal processing, RF, data acquisition, and other applications.  The course will utilize a number of tools and areas of study in pursuit of our work, reflective of the hybrid modern state of the field, so usage of C, Python, shells scripts, signals and systems, communications, and RF concepts, should be expected."
