#:schema ./override-schema.json
# CMS special subjects (fall 2025)

["CMS.S61"]
name = "Special Subject: STEAM Learning Architecture: A Framework for Educational Innovation"
meets = "CMS.S97"
hassS = true
level = "U"
lectureUnits = 2
labUnits = 1
preparationUnits = 9
inCharge = "Claudia Urrea"
description = "This course explores the creation of new learning environments and experiences through the lens of the STEAM Learning Architecture, a framework developed by pk-12 @ Open Learning to guide approaches to teaching and learning for educational innovation. The framework prioritizes student-centered, hands-on learning, rooted in the Constructionist theory that the most powerful learning occurs through discovery, exploration, and creation. Guest speakers and site visits will provide context for final projects that produce innovative learning experiences for k-12 audiences. Class meets Tuesdays 10-12, Recitation is Thursdays 10-11."

["CMS.S97"]
name = "Special Subject: STEAM Learning Architecture: A Framework for Educational Innovation"
meets = "CMS.S61"
level = "G"
lectureUnits = 2
labUnits = 1
preparationUnits = 9
inCharge = "Claudia Urrea"
description = "This course explores the creation of new learning environments and experiences through the lens of the STEAM Learning Architecture, a framework developed by pk-12 @ Open Learning to guide approaches to teaching and learning for educational innovation. The framework prioritizes student-centered, hands-on learning, rooted in the Constructionist theory that the most powerful learning occurs through discovery, exploration, and creation. Guest speakers and site visits will provide context for final projects that produce innovative learning experiences for k-12 audiences. Class meets Tuesdays 10-12, Recitation is Thursdays 10-11."
