#:schema ./override-schema.json
# CMW/21W special subjects (Spring 2025)
# https://cmsw.mit.edu/mit_subject/

['CMS.S60']
name = "Special Subject: Rap Theory and Practice"
same = "21L.S60"
lectureUnits = 3
labUnits = 0
preparationUnits = 9
hassA = true
meets = 'CMS.S96'
description = "To gain a deeper understanding of rap, students engage in the full process of creating rap music, including composing lyrics, recording, performing, and creating an EP length album. Existing rap music is studied, selected lyrics are analyzed, and possible reasons for the structure and success of different songs are presented in case studies. Students analyze rap songs, reflect on their own weekly activities in writing and present their work in class by playing recordings, performing and responding to each other in workshop discussions. Licensed by the Committee on Curricula. Limited to 8."

['CMS.S61']
name = "Special Subject: STEAM Learning Architecture: A Framework for Educational Innovation"
lectureUnits = 3
labUnits = 0
preparationUnits = 9
hassS = true
meets = "CMS.S97"
description = "This course explores the creation of new learning environments and experiences through the lens of the STEAM Learning Architecture, a framework developed by pk-12 @ Open Learning to guide approaches to teaching and learning for educational innovation. The framework prioritizes student-centered, hands-on learning, rooted in the Constructionist theory that the most powerful learning occurs through discovery, exploration, and creation. Guest speakers and site visits will provide context for final projects that produce innovative learning experiences for k-12 audiences."

['21W.S60']
name = "Special Subject: Black Faith: Spirituality and Liberatory Writing for the Oppressed"
lectureUnits = 3
labUnits = 0
preparationUnits = 9
hassA = true
description = "The class will lean on Black Liturgy, viewing Afro-American spirituality as an exemplary force behind liberation movements in the United States and the Caribbean, but Black as a color and as a concept encompasses every shade. This seminar and workshop will be a forum for people of all backgrounds of oppression (religious, racial, class, disability, sexual, gender, etc.). We will use writing as a vehicle to reside and persist amidst oppression and from within “impure” bodies, tainted by the ramifications of oppression. We will read and write experimental and unconventional forms of literature, looking to them as modalities of faith that can operate and thrive within a system in which we have lost faith."
