name: CI checks for the frontend

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.{py,md,txt,toml}"
      - "{.vscode,deploy/cron_scripts,public}/**/*"
      - ".editorconfig"
      - ".gitignore"
      - ".prettierignore"
      - "scrapers/overrides.toml.d/override-schema.json"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.{py,md,txt,toml}"
      - "{.vscode,deploy/cron_scripts,public}/**/*"
      - ".editorconfig"
      - ".gitignore"
      - ".prettierignore"
      - "scrapers/overrides.toml.d/override-schema.json"

jobs:
  prettier:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install node
        uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci
      - name: Run Format
        run: npm run format:check
  lint:
    name: Lint + Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install node
        uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci
      - name: Check types
        run: npm run typecheck
      - name: Run Lint
        run: npm run lint
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install node
        uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
